# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{alea}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aitor Garcia"]
  s.date = %q{2010-09-28}
  s.description = %q{alea is a tiny gem that aim to bring some aleatory behavior to ruby Kernel.}
  s.email = %q{info@linkingpaths.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "HISTORY",
     "LICENSE",
     "Manifest.txt",
     "POSTINSTALL",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "alea.gemspec",
     "config/hoe.rb",
     "config/requirements.rb",
     "lib/alea.rb",
     "lib/alea/kernel.rb",
     "lib/alea/numeric.rb",
     "lib/alea/percentage.rb",
     "lib/alea/range.rb",
     "lib/alea/version.rb",
     "test/test_helper.rb",
     "test/test_kernel.rb",
     "test/test_numeric.rb",
     "test/test_percentage.rb",
     "test/test_range.rb"
  ]
  s.homepage = %q{http://github.com/linkingpaths/alea}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{alea is a tiny gem that aim to bring some aleatory behavior to ruby Kernel.}
  s.test_files = [
    "test/test_helper.rb",
     "test/test_kernel.rb",
     "test/test_numeric.rb",
     "test/test_percentage.rb",
     "test/test_range.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

